stages:
  - build
  - test
  - archive
  - notify


before_script:
  - apt-get update && apt-get install -y google-chrome-stable
  - npm install

build:
  stage: build
  image: node:18
  script:
    - echo "Checkout code"
    - git checkout master

test:
  stage: test
  image: node:18
  script:
    - echo "Run tests"
    - npx wdio run wdio.conf.ts