stages:
  - build
  - test
  - archive
  - notify

variables:
  NODE_VERSION: "18"

before_script:
  - echo "Setting up environment"
  - choco install microsoft-edge -y
  - choco install git -y
  - npm install

build:
  stage: build
  image: mcr.microsoft.com/windows/servercore:ltsc2022
  script:
    - echo "Checkout code"
    - git checkout master

test:
  stage: test
  image: mcr.microsoft.com/windows/servercore:ltsc2022
  script:
    - echo "Run tests"
    - npx wdio wdio.conf.ts
  artifacts:
    paths:
      - '**/reports/**/*'

archive:
  stage: archive
  image: mcr.microsoft.com/windows/servercore:ltsc2022
  script:
    - echo "Archive test reports"
  artifacts:
    when: always
    paths:
      - '**/reports/**/*'

notify:
  stage: notify
  image: mcr.microsoft.com/windows/servercore:ltsc2022
  script:
    - echo "Send email notification"
    - |
      if ($env:CI_JOB_STATUS -eq "success") {
        curl --url 'smtp://smtp.gmail.com:587' --ssl-reqd `
          --mail-from 'loganathansmca2014@gmail.com' `
          --mail-rcpt 'logumca2011@gmail.com' `
          --user 'loganathansmca2014@gmail.com:India@12354' `
          -T ([System.Text.Encoding]::UTF8.GetBytes("Subject: Build Success\n\nThe build was successful!"))
      }
