stages:
  - build
  - test
  - archive
  - notify

variables:
  NODE_VERSION: "18"
  DEBIAN_FRONTEND: noninteractive  # Prevent interactive prompts

before_script:
  - apt-get update
  - apt-get install -y wget gnupg2 curl tzdata
  - ln -fs /usr/share/zoneinfo/Asia/Dubai /etc/localtime  # Set timezone to Dubai
  - dpkg-reconfigure -f noninteractive tzdata
  - wget -q -O - https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  - wget -q https://packages.microsoft.com/config/ubuntu/20.04/prod.list -O /etc/apt/sources.list.d/microsoft-prod.list
  - apt-get update
  - apt-get install -y microsoft-edge-stable
  - npm ci  # Install dependencies efficiently

build:
  stage: build
  image: node:18
  script:
    - echo "Building project..."

test:
  stage: test
  image: node:18
  script:
    - echo "Running tests..."
    - npm ci  # Ensure dependencies are installed before testing
    - npx wdio wdio.conf.ts
  artifacts:
    when: always
    paths:
      - '**/reports/**/*'

archive:
  stage: archive
  image: node:18
  script:
    - echo "Archiving test reports..."
  artifacts:
    when: always
    paths:
      - '**/reports/**/*'

notify:
  stage: notify
  image: node:18
  script:
    - echo "Sending email notification..."
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        curl --url 'smtp://smtp.gmail.com:587' --ssl-reqd \
          --mail-from "$SMTP_USER" \
          --mail-rcpt "$NOTIFY_EMAIL" \
          --user "$SMTP_USER:$SMTP_PASS" \
          -T <(echo -e "Subject: Build Success\n\nThe build was successful!")
      fi
