image: ubuntu:20.04  # Use a supported Ubuntu version


stages:
  - build
  - test
  - archive
  - notify

variables:
  NODE_VERSION: "18"

before_script:
- apt-get update && apt-get install -y curl wget gnupg2
    # Add Microsoft's official GPG key
    - curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /usr/share/keyrings/microsoft.gpg > /dev/null
    # Add Microsoft Edge repository
    - echo "deb [signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" | tee /etc/apt/sources.list.d/microsoft-edge.list
    # Update and install Microsoft Edge Stable
    - apt-get update && apt-get install -y microsoft-edge-stable
    # Download and install EdgeDriver
    - wget -q https://msedgedriver.azureedge.net/$(microsoft-edge --version | awk '{print $3}')/edgedriver_linux64.zip
    - unzip edgedriver_linux64.zip -d /usr/local/bin/
    - chmod +x /usr/local/bin/msedgedriver
  - npm install

build:
  stage: build
  image: node:18
  script:
    - echo "Checkout code"
    - git checkout master

test:
  stage: test
  image: node:18
  script:
    - echo "Run tests"
    - npx wdio wdio.conf.ts
  artifacts:
    paths:
      - '**/reports/**/*'

archive:
  stage: archive
  image: node:18
  script:
    - echo "Archive test reports"
  artifacts:
    when: always
    paths:
      - '**/reports/**/*'

notify:
  stage: notify
  image: node:18
  script:
    - echo "Send email notification"
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        curl --url 'smtp://smtp.gmail.com:587' --ssl-reqd \
          --mail-from 'loganathansmca2014@gmail.com' \
          --mail-rcpt 'logumca2011@gmail.com' \
          --user 'loganathansmca2014@gmail.com:India@12354' \
          -T <(echo -e "Subject: Build Success\n\nThe build was successful!")
      fi