image: ubuntu:20.04  # Use a supported Ubuntu version

stages:
  - install
  - test

install_dependencies:
  stage: install
  script:
    - apt-get update && apt-get install -y curl wget gnupg2
    # Add Microsoft's official GPG key
    - curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /usr/share/keyrings/microsoft.gpg > /dev/null
    # Add Microsoft Edge repository
    - echo "deb [signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" | tee /etc/apt/sources.list.d/microsoft-edge.list
    # Update and install Microsoft Edge Stable
    - apt-get update && apt-get install -y microsoft-edge-stable
    # Download and install EdgeDriver
    - wget -q https://msedgedriver.azureedge.net/$(microsoft-edge --version | awk '{print $3}')/edgedriver_linux64.zip
    - unzip edgedriver_linux64.zip -d /usr/local/bin/
    - chmod +x /usr/local/bin/msedgedriver
  only:
    - master

run_tests:
  stage: test
  script:
    - npm install
    - npm test  # Replace with your actual WebdriverIO command
  only:
    - master
