stages:
  - build
  - test
  - archive
  - notify

variables:
  NODE_VERSION: "18"

before_script:
  - apt-get update
  - apt-get install -y wget gnupg2
  - wget -q -O - https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  - wget -q https://packages.microsoft.com/config/ubuntu/20.04/prod.list -O /etc/apt/sources.list.d/microsoft-prod.list
  - apt-get update
  - apt-get install -y microsoft-edge-stable
  - npm install

build:
  stage: build
  image: node:18
  script:
    - echo "Checkout code"
    - git checkout master

test:
  stage: test
  image: node:18
  script:
    - echo "Run tests"
    - npx wdio wdio.conf.ts
  artifacts:
    paths:
      - '**/reports/**/*'

archive:
  stage: archive
  image: node:18
  script:
    - echo "Archive test reports"
  artifacts:
    when: always
    paths:
      - '**/reports/**/*'

notify:
  stage: notify
  image: node:18
  script:
    - echo "Send email notification"
    - |
      if [ "$CI_JOB_STATUS" == "success" ]; then
        curl --url 'smtp://smtp.gmail.com:587' --ssl-reqd \
          --mail-from 'loganathansmca2014@gmail.com' \
          --mail-rcpt 'logumca2011@gmail.com' \
          --user 'loganathansmca2014@gmail.com:India@12354' \
          -T <(echo -e "Subject: Build Success\n\nThe build was successful!")
      fi
